# Generated by Django 4.2.2 on 2023-06-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt_app', '0002_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
